workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global


version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # temp until a custom docker image with Bash is built
      - run: apk add --update --no-cache bash
      - run:
          name: "Build Docker Images"
          command: ./build-images.sh
      - deploy:
          name: "Publish Docker Images (master branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push cibuilds/github
            fi
